project: esim
namespace: esim
microservices:
  esim:
    name: esim
    image: nginx
    version: 1.1.6
    pullPolicy: Always
    replicaCount: 5
    containerPort: 8080
    containerHZCPort: 5701
    mountPath: /etc/localtime
    volumeName: tz-config
    volumePath: /usr/share/zoneinfo/
    timeZoneValue: America/Lima
    probe:
      readiness:
        path: /management/health
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 10
      liveness:
        path: /management/health
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 10
    configmap:
      env:
        ECOSYSTEM_NAME: esimqr-prod-pe
        DNS_LOGSTASH: 10.84.63.186:5069
        IGNORE_PATTERNS: /(management|swagger|webjars|healthcheck|api/esim/).*|nio-8080|
        TZ: America/Lima
        isDummy: false
        functionRequesterIdentifier: ENPId
        functionCallIdentifier: string
        readTimeout: 2000
        APIM_TOKEN: https://apigee-prodint.entel.pe/auth/oauth/v2/token
        API_CREDENTIAL_TYPE: client_credentials
        PIM_SCOPE: oob
        BASE_LINK: https://esimqr-api.prodmicroservices.entel.pe/api/esim/download_image/
        CONFIRM_ORDER_CONSUMER_ID: 0329AASS100555
        CONFIRM_ORDER_COUNTRY_CODE: PER
        CONFIRM_ORDER_APP_CODE: MIC-SER
        RELEASE_FLAG: false
        URL_PROVIDER_ENDPOINT: https://apigee-prodint.entel.pe/resource/physicalResource/eSimCards/v1/orders/confirm
        hazelcast_instance_name: configuracion
        hazelcast_multicast_enabled: false
        hazelcast_kubernetes_enabled: true
        hazelcast_kubernetes_namespace: esim
        hazelcast_kubernetes_service-name: hazelcast-service
        hazelcast_kubernetes_service-dns: hazelcast-service
        hazelcast_kubernetes_instance-port: 5701
        CORE_POOL_SIZE: 20
        MAX_POOL_SIZE: 20
        QUEUE_CAPACITY: 20
    services:
      esim:
         name: esim-service
         protocol: http
         type: ClusterIP
         port: 80
         targetPort: 8080
         monitor: /management/prometheus
         monitorInterval: 10s
      hazelcast:
         name: hazelcast-service
         protocol: http
         port: 5701
         type: ClusterIP
         targetPort: 5701
    ingress:
      domainName: esimqr-api.prodmicroservices.entel.pe
      certificateName: wildcard
ociSecret:
  name: ocir
