{{- range .Values.microservices }}
{{- $name := .name }}
{{- if .secrets }}

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ .name }}
  namespace: {{ $.Values.namespace }}
  {{- $data := dict "root" . "name" $name }}
  {{- include "template.labels" $data | indent 2 }}
type: Opaque
data:
{{- range $key, $value := .secrets }}
  {{ $key }}: {{ $value }}
{{- end }}
---
{{- end }}
{{- end }}
