apiVersion: v1
kind: Secret
metadata:
  name: apim-clientid-secret-{{ .Values.microservices.esim.name  }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  secret: bmY1bE5RTlZmT0wyNHNsN3VpTWRQVThnd0R3VnFTb29ENFB4bW1jdEd3aHpoMU51
